"""Catalog of functions/symbols and physical constants (CODATA 2018 / SI 2019)."""

# (category, label, description, action)
CATALOG = [
    ("Trigonometry", "sin", "sine", "f:sin("), ("Trigonometry", "cos", "cosine", "f:cos("),
    ("Trigonometry", "tan", "tangent", "f:tan("), ("Trigonometry", "sin⁻¹", "inverse sine", "f:asin("),
    ("Trigonometry", "cos⁻¹", "inverse cosine", "f:acos("), ("Trigonometry", "tan⁻¹", "inverse tangent", "f:atan("),
    ("Hyperbolic", "sinh", "hyperbolic sine", "f:sinh("), ("Hyperbolic", "cosh", "hyperbolic cosine", "f:cosh("),
    ("Hyperbolic", "tanh", "hyperbolic tangent", "f:tanh("), ("Hyperbolic", "sinh⁻¹", "inverse hyperbolic sine", "f:asinh("),
    ("Hyperbolic", "cosh⁻¹", "inverse hyperbolic cosine", "f:acosh("), ("Hyperbolic", "tanh⁻¹", "inverse hyperbolic tangent", "f:atanh("),
    ("Exponent / log", "log", "common logarithm (base 10)", "f:log("), ("Exponent / log", "ln", "natural logarithm", "f:ln("),
    ("Exponent / log", "log□(□)", "logarithm with a base", "tpl:logb"), ("Exponent / log", "10ˣ", "power of ten", "cmd:tenx"),
    ("Exponent / log", "eˣ", "exponential", "cmd:ex"), ("Exponent / log", "exp(", "e to the power", "f:exp("),
    ("Powers / roots", "√□", "square root", "tpl:sqrt"), ("Powers / roots", "∛□", "cube root", "tpl:cbrt"),
    ("Powers / roots", "ⁿ√□", "n-th root", "tpl:root"), ("Powers / roots", "x²", "square", "sup:2"),
    ("Powers / roots", "x³", "cube", "sup:3"), ("Powers / roots", "xʸ", "power", "tpl:sup"),
    ("Powers / roots", "x⁻¹", "reciprocal", "sup:-1"), ("Powers / roots", "|□|", "absolute value", "tpl:abs"),
    ("Calculus", "∫□dx", "definite integral", "tpl:integ"), ("Calculus", "d/dx", "derivative at a point", "tpl:deriv"),
    ("Calculus", "Σ", "summation of f(x)", "tpl:sigma"), ("Calculus", "Π", "product of f(x)", "tpl:prod"),
    ("Fractions", "□/□", "fraction", "tpl:frac"), ("Fractions", "□ □/□", "mixed fraction", "tpl:mixed"),
    ("Number", "Abs(", "absolute value (function form)", "f:abs("), ("Number", "Int(", "integer part (truncate)", "f:int("),
    ("Number", "Intg(", "greatest integer ≤ x", "f:floor("), ("Number", "ceil(", "smallest integer ≥ x", "f:ceil("),
    ("Number", "Frac(", "fractional part", "f:frac("), ("Number", "Rnd(", "round to displayed digits", "f:Rnd("),
    ("Number", "round(x,n)", "round to n decimals", "f:round("), ("Number", "sign(", "sign of x", "f:sign("),
    ("Number", "GCD(", "greatest common divisor", "f:gcd("), ("Number", "LCM(", "least common multiple", "f:lcm("),
    ("Number", "mod(a,b)", "remainder (floored)", "f:mod("), ("Number", "quot(a,b)", "integer quotient", "f:quot("),
    ("Number", "rem(a,b)", "remainder (truncated)", "f:rem("), ("Number", "x!", "factorial", "t:!"),
    ("Number", "nPr", "permutations", "t:nPr"), ("Number", "nCr", "combinations", "t:nCr"),
    ("Number", "Ran#", "random number 0–0.999", "t:Ran#"), ("Number", "RanInt(a,b)", "random integer", "f:RanInt("),
    ("Number", "%", "percent (÷100)", "t:%"),
    ("Statistics", "min(", "smallest", "f:min("), ("Statistics", "max(", "largest", "f:max("),
    ("Statistics", "avg(", "average", "f:avg("), ("Statistics", "sum(", "sum", "f:sum("),
    ("Angle", "°", "degree mark", "t:°"), ("Angle", "′", "minute mark", "t:′"), ("Angle", "″", "second mark", "t:″"),
    ("Angle", "▸DMS(", "show value as ° ′ ″", "f:dms("), ("Angle", "Pol(x,y)", "rectangular → polar", "f:Pol("),
    ("Angle", "Rec(r,θ)", "polar → rectangular", "f:Rec("), ("Angle", "degrees(", "radians → degrees", "f:degrees("),
    ("Angle", "radians(", "degrees → radians", "f:radians("),
    ("Complex", "i", "imaginary unit", "t:i"), ("Complex", "∠", "polar angle  r∠θ", "t:∠"),
    ("Complex", "Arg(", "argument", "f:arg("), ("Complex", "Conjg(", "conjugate", "f:conjg("),
    ("Complex", "Re(", "real part", "f:re("), ("Complex", "Im(", "imaginary part", "f:im("),
    ("Matrix", "MatA", "matrix A", "t:MatA"), ("Matrix", "MatB", "matrix B", "t:MatB"),
    ("Matrix", "MatC", "matrix C", "t:MatC"), ("Matrix", "MatD", "matrix D", "t:MatD"),
    ("Matrix", "MatAns", "last matrix result", "t:MatAns"), ("Matrix", "Det(", "determinant", "f:Det("),
    ("Matrix", "Trn(", "transpose", "f:Trn("), ("Matrix", "Ide(n)", "identity matrix", "f:Ide("),
    ("Matrix", "Rref(", "reduced row echelon form", "f:Rref("), ("Matrix", "x⁻¹", "inverse (use the ^-1 key)", "sup:-1"),
    ("Vector", "VctA", "vector A", "t:VctA"), ("Vector", "VctB", "vector B", "t:VctB"),
    ("Vector", "VctC", "vector C", "t:VctC"), ("Vector", "VctD", "vector D", "t:VctD"),
    ("Vector", "VctAns", "last vector result", "t:VctAns"), ("Vector", "Dot(", "dot product", "f:Dot("),
    ("Vector", "Cross(", "cross product", "f:Cross("), ("Vector", "Angle(", "angle between vectors", "f:Angle("),
    ("Vector", "UnitV(", "unit vector", "f:UnitV("), ("Vector", "Abs(", "vector length", "f:abs("),
    ("Base-N", "and", "bitwise AND", "t:and"), ("Base-N", "or", "bitwise OR", "t:or"),
    ("Base-N", "xor", "bitwise XOR", "t:xor"), ("Base-N", "xnor", "bitwise XNOR", "t:xnor"),
    ("Base-N", "Not(", "bitwise NOT", "f:Not("), ("Base-N", "Neg(", "two's complement", "f:Neg("),
    ("Symbols", "π", "pi", "t:π"), ("Symbols", "e", "Euler's number", "t:e"),
    ("Symbols", "Ans", "last answer", "t:Ans"), ("Symbols", "PreAns", "answer before last", "t:PreAns"),
    ("Symbols", "=", "equals (for SOLVE)", "t:="), ("Symbols", "<", "less than", "t:<"), ("Symbols", ">", "greater than", "t:>"),
    ("Symbols", "≤", "less or equal", "t:≤"), ("Symbols", "≥", "greater or equal", "t:≥"), ("Symbols", "≠", "not equal", "t:≠"),
    ("Symbols", "→", "store into variable", "t:→"),
]

# (name, symbol, value string, unit)
CONSTANTS = [
    ("Speed of light in vacuum", "c", "299792458", "m/s"),
    ("Planck constant", "h", "6.62607015E-34", "J·s"),
    ("Reduced Planck constant", "ħ", "1.054571817E-34", "J·s"),
    ("Elementary charge", "e", "1.602176634E-19", "C"),
    ("Boltzmann constant", "k", "1.380649E-23", "J/K"),
    ("Avogadro constant", "N_A", "6.02214076E23", "1/mol"),
    ("Molar gas constant", "R", "8.314462618", "J/(mol·K)"),
    ("Gravitational constant", "G", "6.6743E-11", "m³/(kg·s²)"),
    ("Standard gravity", "g", "9.80665", "m/s²"),
    ("Electron mass", "mₑ", "9.1093837015E-31", "kg"),
    ("Proton mass", "mₚ", "1.67262192369E-27", "kg"),
    ("Neutron mass", "mₙ", "1.67492749804E-27", "kg"),
    ("Muon mass", "m_μ", "1.883531627E-28", "kg"),
    ("Atomic mass unit", "u", "1.66053906660E-27", "kg"),
    ("Vacuum permittivity", "ε₀", "8.8541878128E-12", "F/m"),
    ("Vacuum permeability", "μ₀", "1.25663706212E-6", "N/A²"),
    ("Coulomb constant", "kₑ", "8.9875517923E9", "N·m²/C²"),
    ("Stefan–Boltzmann constant", "σ", "5.670374419E-8", "W/(m²·K⁴)"),
    ("Faraday constant", "F", "96485.33212", "C/mol"),
    ("Bohr radius", "a₀", "5.29177210903E-11", "m"),
    ("Bohr magneton", "μ_B", "9.2740100783E-24", "J/T"),
    ("Nuclear magneton", "μ_N", "5.0507837461E-27", "J/T"),
    ("Classical electron radius", "rₑ", "2.8179403262E-15", "m"),
    ("Compton wavelength", "λ_C", "2.42631023867E-12", "m"),
    ("Fine-structure constant", "α", "7.2973525693E-3", ""),
    ("Rydberg constant", "R∞", "10973731.568160", "1/m"),
    ("Wien displacement constant", "b", "2.897771955E-3", "m·K"),
    ("Standard atmosphere", "atm", "101325", "Pa"),
    ("Molar volume (ideal gas, 273.15 K)", "V_m", "0.02241396954", "m³/mol"),
    ("Electron volt", "eV", "1.602176634E-19", "J"),
    ("Josephson constant", "K_J", "4.835978484E14", "Hz/V"),
    ("von Klitzing constant", "R_K", "25812.80745", "Ω"),
    ("Magnetic flux quantum", "Φ₀", "2.067833848E-15", "Wb"),
    ("Conductance quantum", "G₀", "7.748091729E-5", "S"),
    ("Hartree energy", "E_h", "4.3597447222071E-18", "J"),
]
